"""SQLite database layer for the file organizer."""

from src.db.connection import get_db, get_db_connection
from src.db.models import Area, Batch, Document, House, Page, Tenant
from src.db.repository import (
    Repository,
    add_area,
    add_document,
    add_house,
    add_pages_bulk,
    add_tenant,
    create_batch,
    get_active_tenant,
    get_area,
    get_batch,
    get_document,
    get_house,
    get_pages_by_batch,
    link_pages_to_document,
    list_areas,
    list_batches_by_house,
    list_documents_by_category,
    list_documents_by_house,
    list_houses_by_area,
    list_tenants_by_house,
    update_batch_status,
    update_page_cleaning,
    update_document,
    reset_document_manual_lock,
    copy_document,
    batch_copy_documents,
    get_or_create_numbered_folder,
)
from src.db.schema import INDICES_SQL, SCHEMA_SQL, init_db

__all__ = [
    "get_db_connection",
    "get_db",
    "init_db",
    "SCHEMA_SQL",
    "INDICES_SQL",
    "Area",
    "House",
    "Tenant",
    "Batch",
    "Document",
    "Page",
    "Repository",
    "add_area",
    "get_area",
    "list_areas",
    "add_house",
    "get_house",
    "list_houses_by_area",
    "add_tenant",
    "get_active_tenant",
    "list_tenants_by_house",
    "create_batch",
    "get_batch",
    "update_batch_status",
    "list_batches_by_house",
    "add_pages_bulk",
    "get_pages_by_batch",
    "update_page_cleaning",
    "link_pages_to_document",
    "add_document",
    "get_document",
    "list_documents_by_house",
    "list_documents_by_category",
    "update_document",
    "reset_document_manual_lock",
    "copy_document",
    "batch_copy_documents",
    "get_or_create_numbered_folder",
]
